jnotes/jnotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

jnotes/notes/urls.py
from django.urls import path

from .views import HomeView, NoteDetailView, NoteAddView, NoteDeleteView, NoteUpdateView
from .views import CategoriesList, OneCategoryList
from .views import DonationPageView

from .views import RegisterView,LoginView, LogoutView, test

# устанавливаем пространство имени приложения( но мы выбрали дефолтное значение, могли и не менять)
# выходит, чтобы обратиться к шаблоного данного приложения нужно обращаться через notes:
app_name = 'notes'

# маршрутизатор
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('note/<int:pk>', NoteDetailView.as_view(), name='note-detail'),
    path('add_note/', NoteAddView.as_view(), name='note-add'),
    path('note/<int:pk>/remove', NoteDeleteView.as_view(), name='note-delete'),
    path('note/<int:pk>/update', NoteUpdateView.as_view(), name='note-update'),
    path('categories/', CategoriesList.as_view(), name='categories-view'),
    path('category/<int:choice>', OneCategoryList.as_view(), name='one-category'),
    path('donation/', DonationPageView.as_view(), name='donation'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('',test, name='checking'),


]
# as_view() используюется, если мы используем базовые view из generic'a

jnotes/notes/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import datetime


# модель для создания категорий
class Category(models.Model):
    name = models.CharField(max_length=255,  unique=True, editable=True)

    # метод возвращает строковое представление
    def __str__(self):
        return self.name

    # Метод, который переводит все в нижний регистр.
    # Теперь не имеет значения, в каком регистре все вводится
    def clean(self):

        self.name = self.name.lower()

    # использую класс для того, чтобы преобразовать нужные данные в админке
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']


# модель для создания аттрибутов заметки


class Note(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    title_note = models.CharField(blank=True, max_length=150, verbose_name='Заголовок')
    category_note = models.ForeignKey(Category, blank=True, on_delete=models.CASCADE, verbose_name='категория')
    content_note = models.TextField(blank=True, verbose_name='Контент')
    date_note = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')


    # функция позволяет обработать введенные данные


    def get_absolute_url(self):
        return reverse('notes:home')

    # строковое представление
    def __str__(self):
        formatted_time = datetime.strftime(self.date_note, "%d.%m.%Y")
        formatted_view = self.title_note + '|' + str(self.category_note) + '->' + formatted_time
        return formatted_view

    # использую класс для того, чтобы преобразовать нужные данные в админке
    class Meta:
        verbose_name = 'Заметка'
        verbose_name_plural = 'Заметки'
        ordering = ['-date_note']

jnotes/notes/forms.py
from django import forms
from django.db import models

from .models import Note, Category
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя',
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))




class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя',
                               widget=forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Подтверждение пароля',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


# добавляем временное поле, чтобы при выборе категории был не селектор, а простое поле для ввода
class CreateForm(forms.Form):
    title = forms.CharField(max_length=150, required=False, label='Заголовок',
                            widget=forms.TextInput(attrs={'class': 'post-title inputs'}))
    category = forms.CharField(max_length=150, required=False, label='Категория',
                               widget=forms.TextInput(attrs={'class': 'post-category inputs'}))
    content = forms.CharField(label='Контент', widget=forms.Textarea(attrs={'class': 'post-content inputs'}))

    def clean_title(self):
        if not self.cleaned_data['title']:
            self.cleaned_data['title'] = 'NoTitle'
        return self.cleaned_data['title']

    def clean_category(self):
        if not self.cleaned_data['category']:
            self.cleaned_data['category'] = 'void'
        return self.cleaned_data['category']

jnotes/notes/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, DetailView, UpdateView
from django.views.generic import CreateView, DeleteView, View
from django.contrib.auth import login, logout
from .models import Note, Category
from django.contrib.auth.models import User
from .forms import CreateForm, UserRegisterForm, UserLoginForm
from django.db.models import Q

# контрольно-пропускной пункт на сервис//проверка на авторизацию
def test(request):
    if request.user.is_authenticated:
        return redirect("notes:home")
    return redirect("notes:register")

# выход из аккаунта//использую встроенную библиотеку для этого
class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('notes:checking')

# регистрация аккаунта и сразву авторизация
class RegisterView(View):
    def post(self, request):
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'ого вау')
            return redirect('notes:home')
        else:

            return render(request, 'notes/register.html', {'form': form})

    def get(self, request):
        form = UserRegisterForm()
        return render(request, 'notes/register.html', {'form': form})

# вход в аккаунт
class LoginView(View):
    def post(self, request):
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)

            return redirect('notes:home')
        else:
            return render(request, 'notes/login.html', {'form': form})

    def get(self, request):
        form = UserLoginForm()
        return render(request, 'notes/login.html', {'form': form})


# вывод шаблона для донатов
class DonationPageView(View):
    def get(self, request, *args, **kwargs):
        return render(request=request, template_name='notes/donation.html')


# основная страница, со всеми заметками
class HomeView(ListView):
    model = Note
    template_name = 'notes/home.html'
    ordering = ['-date_note']
    context_object_name = 'notes_list'

    # paginate_by = 2  это на случай пагинации
    def get_queryset(self):
        if self.request.user.is_active:
            return Note.objects.filter(author=self.request.user).select_related('category_note')


# содержание заметки
class NoteDetailView(DetailView):
    model = Note
    template_name = 'notes/note-detail.html'
    context_object_name = 'note'


# создание заметки
class NoteAddView(View):
    def post(self, request, *args, **kwargs):
        form = CreateForm(request.POST)
        if form.is_valid():
            chosen_category = Category.objects.get_or_create(name=form.cleaned_data['category'])
            Note.objects.create(title_note=form.cleaned_data['title'],
                                category_note=Category(chosen_category[0]).pk,
                                content_note=form.cleaned_data['content'],
                                author=User(request.user.pk)
                                )
            return redirect('notes:home')

    def get(self, request):
        if request.user.is_authenticated:
            form = CreateForm()
            return render(request, 'notes/note-add.html', {'form': form})
        else:
            return HttpResponse('<h1>suck ma d</h1>')


# удаление заметки
class NoteDeleteView(DeleteView):
    model = Note

    success_url = reverse_lazy('notes:home')

    # чтобы удалить заметку сразу, без перехода на другой шаблон
    def get(self, *args, **kwargs):
        messages.success(self.request, 'ddddd')
        return self.post(*args, **kwargs)


# Обновление заметки
class NoteUpdateView(View):
    def post(self, request, *args, **kwargs):
        form = CreateForm(request.POST)
        if form.is_valid():
            chosen_category = Category.objects.get_or_create(name=form.cleaned_data['category'])
            chosen_note = Note.objects.get(pk=self.kwargs['pk'])
            chosen_note.title_note = form.cleaned_data['title']
            chosen_note.category_note = Category(chosen_category[0]).pk
            chosen_note.content_note = form.cleaned_data['content']
            chosen_note.save()
            return redirect('notes:home')

    def get(self, request, *args, **kwargs):
        chosen_note = Note.objects.get(pk=self.kwargs['pk'])
        data = {
            'title': chosen_note.title_note,
            'category': chosen_note.category_note,
            'content': chosen_note.content_note,
        }
        form = CreateForm(data)
        return render(request, 'notes/note-add.html', {'form': form})


# вывод всех существующих категорий в блоке "все категории"
class CategoriesList(View):
    def get(self, request, *args, **kwargs):
        for item in Category.objects.all():  # цикл удаляет категории у которых нет записей
            if len(Note.objects.filter(category_note_id=item.pk)) == 0:
                Category.objects.get(name=item).delete()
        all_categories = Category.objects.order_by('name')
        author_categories = []
        for category in all_categories:
            categories_notes = category.note_set.all()

            for note in categories_notes:
                if note.author == self.request.user:
                    pull_out = Category.objects.get(name=note.category_note)
                    if pull_out not in author_categories:
                        author_categories.append(pull_out)

        return render(request, 'notes/categories_list.html', {'categories': author_categories})


# вывод все существующих заметок выбранной категории
class OneCategoryList(View):
    def get(self, request, choice):
        category_posts = Note.objects.filter(Q(category_note=choice) & Q(author=self.request.user))
        return render(request, 'notes/home.html', {'notes_list': category_posts})

# order_by() - отсортировать по определенному полю
# values(name) - получить  объекты одного поля
# values_list(name) - получить все объекты одного поля в формате листа

jnotes/notes/templates/notes/authorization.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/authorization.css' %}">
    <title>Document</title>
</head>
<body>
<h2>Улыбка Жокера</h2>
<div class="container" id="container">
    <div class="form-container sign-up-container">
        <form method="post" name="#ccc">
            <h1>El problema</h1>
            {% csrf_token %}
            <input type="text" name="username">
            <input type="password" name="password1">
            <input type="password" name="password2">
            <input type="hidden" name="metadata" value="register">


            <button>Sign In</button>
        </form>
    </div>
    <div class="form-container sign-in-container">
        <form method="post">
            <h1>Sign in</h1>
            {% csrf_token %}
            {{ form.as_table }}
            <input type="hidden" name="metadata" value="login">


            <button>Sign In</button>
        </form>
    </div>
    <div class="overlay-container">
        <div class="overlay">
            <div class="overlay-panel overlay-left">
                <h1>Welcome Back!</h1>
                <p>To keep connected with us please login with your personal info</p>
                <button class="ghost" id="signIn">Sign In</button>
            </div>
            <div class="overlay-panel overlay-right">
                <h1>Hello, Friend!</h1>
                <p>Enter your personal details and start journey with us</p>
                <button class="ghost" id="signUp">Sign Up</button>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/authorization.js' %}"></script>
</body>
</html>

jnotes/notes/templates/notes/categories_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} All categories {% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/categories_list.css' %}">
{% include 'inc/_search_field.html' %}

<div class="container categories-container">
    <div class="row">
        {% for category in categories %}

        <p class="various-categories">&bull; <a class='col-12' href="{%  url 'notes:one-category' category.pk %}">{{ category }}</a></p>

        {% endfor %}
    </div>
</div>

{% endblock %}

jnotes/notes/templates/notes/donation.html
{% extends 'base.html' %}
{% block title %}Donation{% endblock %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/donation.css' %}">
<div class="container">
    <div class="row">
        <iframe class="panel"
                src="https://yoomoney.ru/quickpay/shop-widget?writer=seller&targets=%22OOO DrinkWater%22&targets-hint=&default-sum=10&button-text=14&payment-type-choice=on&comment=on&hint=&successURL=&quickpay=shop&account=4100116577503954"
                width="423" height="301" frameborder="0" allowtransparency="true" scrolling="no"></iframe>
    </div>
</div>

{% endblock %}  

jnotes/notes/templates/notes/home.html
{% extends 'base.html' %}
{% block title %} Jnotes {% endblock %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% include 'inc/_search_field.html' %}
<div class="container card-container">
    <div class="row justify-content-center">
    {% if notes_list %}
        {% for post in notes_list %}

        <div onclick="window.location='{% url 'notes:note-detail' post.pk %}'" class="card col-md-12 col-12x">
            <div class="card-body">
                <div class="card-delete">
                    <a href="{% url 'notes:note-delete' post.pk %}">
                        <i class="fas fa-times fa-2x"></i>
                    </a>
                </div>

                <h5 class="card-title">{{ post.title_note }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ post.category_note }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">{{ post.date_note|date:"d/m/Y" }}</h6>
                <h6>{{ post.author }}</h6>
                <p class="card-text">{{ post.content_note|truncatechars:150 }}</p>


            </div>
        </div>

        {% endfor %}
        {% else %}
        <p class="h1 justify-content">ahahahahahahah</p>
        {% endif %}
    </div>
</div>
{% endblock %}

jnotes/notes/templates/notes/login.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap-5/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/authorization.css' %}">
    <title>Авторизация</title>
</head>
<body>
<div class="container col-12 col-md-8 col-lg-6 col-xl-6">
    <div class="row">
        <h1 class="text-center">Авторизация</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><a href="{% url 'notes:register' %}">Зарегистрироваться</a></p>
            <div class="text-center">
                <button type="submit" class="btn btn-dark">Войти</button>
            </div>

        </form>

    </div>
</div>

</body>
</html>

jnotes/notes/templates/notes/note-add.html
{% extends 'base.html' %}
{% load static %}
{% load my_filter %}
{% block title %}master{% endblock %}


{% block content %}
<link rel="stylesheet" href="{% static 'css/note_add.css' %}">
<div class="container">
    <div class="row">
        <form method="POST" class="new-post">
            {% csrf_token %}
            {% for item in form %}
            <div class="field">
                {{ item.label_tag }}
                {{ item }}
            </div>

            {% endfor %}

            <div class="col-md-12 text-center">
                <button class="btn btn-secondary btn-lg btn-block">Save</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

jnotes/notes/templates/notes/note-detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %} note: {{ note.title_note }} {% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/note-detail.css' %}">
<div class="container">
    <div class="row">
        <div class="text-block">
            <h1>{{ note.title_note }}/<a href="{% url 'notes:one-category' note.category_note.pk %}">{{ note.category_note }}</a></h1>
            <p>{{ note.date_note|date:"d/m/Y" }}</p>
            <a href="{% url 'notes:note-update' note.pk %}">Fuck</a>
            <p class="note_date">{{ note.content_note|linebreaks }}</p>
        </div>
    </div>
</div>

{% endblock %}

jnotes/notes/templates/notes/note-update.html
{% extends 'base.html' %}
{% load static %}
{% load my_filter %}
{% block title %}master{% endblock %}


{% block content %}
<link rel="stylesheet" href="{% static 'css/note_add.css' %}">
<div class="container">
    <div class="row">
        <form method="POST" class="new-post">
            {% csrf_token %}
            <div class="field">
            <p class="h2">Title:</p>
            {{ form.title_note|addclass:'post-title inputs' }}
            </div>
            <div class="field">
            <p class="h2">Category:</p>
            {{ form.temp_category|addclass:'post-category inputs' }}
            </div>
            <div class="field">
            <p class="h2">Content:</p>
            {{ form.content_note|addclass:'post-content inputs' }}
            </div>
            <div class="col-md-12 text-center">
            <button class="btn btn-secondary btn-lg btn-block">Update</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

jnotes/notes/templates/notes/register.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap-5/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/authorization.css' %}">
    <title>Регистрация</title>
</head>
<body>
<div class="container col-12 col-md-8 col-lg-6 col-xl-6">
    <div class="row">
        <h1 class="text-center">Регистрация</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><a href="{% url 'notes:login' %}">у меня уже есть аккаунт</a></p>
            <div class="text-center">
                <button type="submit" class="btn btn-dark">Войти</button>
            </div>
        </form>

    </div>
</div>

</body>
</html>