jnotes/jnotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

jnotes/notes/urls.py
from django.urls import path

from .views import HomeView, NoteDetailView, NoteAddView, NoteDeleteView, NoteUpdateView
from .views import CategoriesList, OneCategoryList
from .views import DonationPageView

from .views import RegisterView,LoginView, LogoutView, test

# устанавливаем пространство имени приложения( но мы выбрали дефолтное значение, могли и не менять)
# выходит, чтобы обратиться к шаблоного данного приложения нужно обращаться через notes:
app_name = 'notes'

# маршрутизатор
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('note/<int:pk>', NoteDetailView.as_view(), name='note-detail'),
    path('add_note/', NoteAddView.as_view(), name='note-add'),
    path('note/<int:pk>/remove', NoteDeleteView.as_view(), name='note-delete'),
    path('note/<int:pk>/update', NoteUpdateView.as_view(), name='note-update'),
    path('categories/', CategoriesList.as_view(), name='categories-view'),
    path('category/<int:choice>', OneCategoryList.as_view(), name='one-category'),
    path('donation/', DonationPageView.as_view(), name='donation'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('',test, name='checking'),


]
# as_view() используюется, если мы используем базовые view из generic'a

jnotes/templates/inc/_nav.html
<div class="container-fluid">
    <div class="row">
        <div class="col-12" style="padding:0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'notes:home' %}">JNotes</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        {% with request.resolver_match.url_name as url_name %}
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="#">Global notes</a>
                            </li>
                            {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link {% if url_name == 'home' %}active{% endif %}" aria-current="page"
                                   href="{% url 'notes:home' %}">Local Notes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if url_name == 'categories-view' %}active{% endif %}"
                                   href="{% url 'notes:categories-view' %}">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if url_name == 'note-add' %}active{% endif %}"
                                   href="{% url 'notes:note-add' %}">New note</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link {% if url_name == 'donation' %}active{% endif %}"
                                   href="{% url 'notes:donation' %}">Feed the creators</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link {% if url_name == 'logout' %}active{% endif %}"
                                   href="{% url 'notes:logout' %}">{{ user.username }}, get out from here</a>
                            </li>
                        </ul>

                        {% else %}
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'notes:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'notes:register' %}">Register</a>

                            </li>
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
{% endwith %}

jnotes/templates/inc/_search_field.html
<div class="container sfield-container">
    <div class="row">
        <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</div>